import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "ReCopyFast - Universal CMS Layer",
    short_name: "ReCopyFast",
    description:
      "Transform any website into an editable platform with a simple script tag",
    start_url: "/",
    scope: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: "#2563eb",
    // Generated by `src/app/icon.tsx`. Chrome requires both a 192px and a
    // 512px icon before it will offer to install the app.
    icons: [
      {
        src: "/icon/192",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon/512",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
    ],
  };
}
