-- ========================================
-- s89 review fix — claim the daily generation before spending the provider call
-- ========================================
-- ADR 057's `blog_posts.generated_on` unique index prevents two rows, but it is
-- reached only after OpenAI has answered. The independent review forced two
-- deliveries past the pre-read together: both paid for generation, then one lost
-- at the index. This separate ledger moves the race boundary before OpenAI.
--
-- There is deliberately no lease expiry or automatic takeover. OpenAI offers no
-- request idempotency key here; a slow/crashed request may still charge after our
-- function stops waiting. Stealing an old claim would recreate the duplicate-call
-- defect. Pending and failed claims are recovered explicitly by an operator using
-- docs/operations/blog.md (ADR 060).

CREATE TABLE IF NOT EXISTS public.blog_generation_claims (
  generated_on DATE PRIMARY KEY,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'succeeded', 'failed')),
  -- Generated by the application for one invocation and never returned to a web
  -- caller. It proves which claimant may finalize or fail this day.
  owner_token UUID NOT NULL,
  post_id UUID REFERENCES public.blog_posts(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  CONSTRAINT blog_generation_claims_state_consistent CHECK (
    (status = 'pending' AND post_id IS NULL AND completed_at IS NULL)
    OR (status = 'succeeded' AND post_id IS NOT NULL AND completed_at IS NOT NULL)
    OR (status = 'failed' AND post_id IS NULL AND completed_at IS NOT NULL)
  )
);

COMMENT ON TABLE public.blog_generation_claims IS
  'Service-role-only UTC-day claims that prevent overlapping blog cron deliveries from calling OpenAI twice (s89, ADR 060).';
COMMENT ON COLUMN public.blog_generation_claims.owner_token IS
  'Opaque per-invocation UUID required to finalize or fail a pending claim; never exposed to web principals.';

ALTER TABLE public.blog_generation_claims ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role reads blog generation claims"
  ON public.blog_generation_claims;
CREATE POLICY "Service role reads blog generation claims"
  ON public.blog_generation_claims
  FOR SELECT
  TO service_role
  USING (true);

-- Revoke table-level and inherited/default grants before adding the one reviewed
-- projection. A web principal must not see claim state or owner tokens, and product
-- writes go through the token-checking functions below rather than direct DML.
REVOKE ALL ON TABLE public.blog_generation_claims
  FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON TABLE public.blog_generation_claims TO service_role;

CREATE OR REPLACE FUNCTION public.claim_daily_blog_generation(
  p_generated_on DATE,
  p_owner_token UUID
)
RETURNS TABLE(outcome TEXT, claim_status TEXT, post_id UUID)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_inserted INTEGER;
  v_owner_token UUID;
  v_status TEXT;
  v_post_id UUID;
BEGIN
  IF p_generated_on IS NULL OR p_owner_token IS NULL THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = 'daily blog generation needs a day and owner token';
  END IF;

  -- This lock is held for a few local statements only. It serializes the legacy
  -- post check with claim creation; it never spans the provider request.
  PERFORM pg_advisory_xact_lock(
    hashtextextended('blog_generation:' || p_generated_on::TEXT, 0)
  );

  -- A row from the pre-claim deployment already fulfils the day. Materialize a
  -- succeeded claim around it so every later delivery returns it without OpenAI.
  SELECT post.id INTO v_post_id
  FROM public.blog_posts AS post
  WHERE post.generated_on = p_generated_on;

  IF v_post_id IS NOT NULL THEN
    INSERT INTO public.blog_generation_claims AS claim (
      generated_on, status, owner_token, post_id, completed_at
    ) VALUES (
      p_generated_on, 'succeeded', p_owner_token, v_post_id, NOW()
    )
    ON CONFLICT (generated_on) DO UPDATE
      SET status = 'succeeded',
          post_id = EXCLUDED.post_id,
          updated_at = NOW(),
          completed_at = COALESCE(claim.completed_at, NOW());

    RETURN QUERY SELECT 'existing'::TEXT, 'succeeded'::TEXT, v_post_id;
    RETURN;
  END IF;

  INSERT INTO public.blog_generation_claims (
    generated_on, status, owner_token
  ) VALUES (
    p_generated_on, 'pending', p_owner_token
  )
  ON CONFLICT (generated_on) DO NOTHING;
  GET DIAGNOSTICS v_inserted = ROW_COUNT;

  SELECT claim.owner_token, claim.status, claim.post_id
    INTO v_owner_token, v_status, v_post_id
  FROM public.blog_generation_claims AS claim
  WHERE claim.generated_on = p_generated_on;

  RETURN QUERY SELECT
    CASE
      WHEN v_inserted = 1 OR (v_status = 'pending' AND v_owner_token = p_owner_token)
        THEN 'acquired'::TEXT
      ELSE 'existing'::TEXT
    END,
    v_status,
    v_post_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.complete_daily_blog_generation(
  p_generated_on DATE,
  p_owner_token UUID,
  p_title TEXT,
  p_slug TEXT,
  p_content TEXT,
  p_excerpt TEXT,
  p_category TEXT
)
RETURNS TABLE(
  created BOOLEAN,
  id UUID,
  title TEXT,
  slug TEXT,
  category TEXT,
  status TEXT,
  excerpt TEXT,
  generated_on DATE,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_claim_owner UUID;
  v_claim_status TEXT;
  v_created BOOLEAN := FALSE;
  v_post public.blog_posts%ROWTYPE;
BEGIN
  IF p_generated_on IS NULL
     OR p_owner_token IS NULL
     OR NULLIF(btrim(p_title), '') IS NULL
     OR NULLIF(btrim(p_slug), '') IS NULL
     OR NULLIF(btrim(p_content), '') IS NULL
     OR NULLIF(btrim(p_category), '') IS NULL THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = 'daily blog completion received invalid input';
  END IF;

  SELECT claim.owner_token, claim.status
    INTO v_claim_owner, v_claim_status
  FROM public.blog_generation_claims AS claim
  WHERE claim.generated_on = p_generated_on
  FOR UPDATE;

  IF v_claim_owner IS NULL
     OR v_claim_owner <> p_owner_token
     OR v_claim_status <> 'pending' THEN
    RAISE EXCEPTION USING
      ERRCODE = '42501',
      MESSAGE = 'daily blog claim is not owned by this invocation';
  END IF;

  -- A pre-claim deployment may have inserted while this owner generated. Reuse
  -- that row instead of creating a second one; the day key remains the backstop.
  SELECT post.* INTO v_post
  FROM public.blog_posts AS post
  WHERE post.generated_on = p_generated_on;

  IF v_post.id IS NULL THEN
    BEGIN
      INSERT INTO public.blog_posts AS post (
        title, slug, content, excerpt, category,
        status, published_at, generated_on
      ) VALUES (
        p_title, p_slug, p_content, p_excerpt, p_category,
        'draft', NULL, p_generated_on
      )
      RETURNING post.* INTO v_post;
      v_created := TRUE;
    EXCEPTION
      WHEN unique_violation THEN
        -- A unique violation can be the day (reuse its row) or an old post's
        -- slug. Preserve s89's one retry with the UTC day appended.
        SELECT post.* INTO v_post
        FROM public.blog_posts AS post
        WHERE post.generated_on = p_generated_on;

        IF v_post.id IS NULL THEN
          INSERT INTO public.blog_posts AS post (
            title, slug, content, excerpt, category,
            status, published_at, generated_on
          ) VALUES (
            p_title, p_slug || '-' || p_generated_on::TEXT,
            p_content, p_excerpt, p_category,
            'draft', NULL, p_generated_on
          )
          RETURNING post.* INTO v_post;
          v_created := TRUE;
        END IF;
    END;
  END IF;

  UPDATE public.blog_generation_claims AS claim
     SET status = 'succeeded',
         post_id = v_post.id,
         updated_at = NOW(),
         completed_at = NOW()
   WHERE claim.generated_on = p_generated_on
     AND claim.owner_token = p_owner_token
     AND claim.status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION USING
      ERRCODE = '40001',
      MESSAGE = 'daily blog claim changed before completion';
  END IF;

  RETURN QUERY SELECT
    v_created,
    v_post.id,
    v_post.title,
    v_post.slug,
    v_post.category,
    v_post.status,
    v_post.excerpt,
    v_post.generated_on,
    v_post.published_at,
    v_post.created_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.fail_daily_blog_generation(
  p_generated_on DATE,
  p_owner_token UUID
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_updated INTEGER;
BEGIN
  IF p_generated_on IS NULL OR p_owner_token IS NULL THEN
    RETURN FALSE;
  END IF;

  UPDATE public.blog_generation_claims AS claim
     SET status = 'failed',
         post_id = NULL,
         updated_at = NOW(),
         completed_at = NOW()
   WHERE claim.generated_on = p_generated_on
     AND claim.owner_token = p_owner_token
     AND claim.status = 'pending';
  GET DIAGNOSTICS v_updated = ROW_COUNT;
  RETURN v_updated = 1;
END;
$$;

-- Supabase exposes public-schema functions through PostgREST. Default EXECUTE is
-- PUBLIC, so every identity is revoked explicitly before the one trusted role.
REVOKE ALL ON FUNCTION public.claim_daily_blog_generation(DATE, UUID)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.complete_daily_blog_generation(
  DATE, UUID, TEXT, TEXT, TEXT, TEXT, TEXT
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.fail_daily_blog_generation(DATE, UUID)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.claim_daily_blog_generation(DATE, UUID)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_daily_blog_generation(
  DATE, UUID, TEXT, TEXT, TEXT, TEXT, TEXT
) TO service_role;
GRANT EXECUTE ON FUNCTION public.fail_daily_blog_generation(DATE, UUID)
  TO service_role;
